### ISSUE TITLE
Duplicated program in one collection.

### ISSUE THREAD

**Issue by TalalE** [ABenchM/abm#108]
Adding programs to an collection did not check if the program is already exists in that Collection or not. So the program could be duplicated in one collection.

**Comment by nguyenLisa** [comment]
You can have twice the same project in a collection. Just make sure that the commit IDs are different as well.

**Comment by ankur-1989** [comment]
As we know, Hermes and Build Collection will soon be part of Delphi along with the crawling of projects to make a new collection and ABM will only be managing collections. ABM will get the collection from Delphi only. After discussion with @nguyenLisa, I got to know that in Delphi, we are maintaining a separate ProjectId along with CommitId which will help in maintaining unique projects in a collection @bhermann Could you please confirm on this?
 In order to avoid duplicate projects in ABM, we will have to provide a check while copying the collection from Delphi to ABM. 
@nguyenLisa Could we put this issue on stall then by that time?

**Comment by ankur-1989** [comment]
Now there is no concept of commit Id in the current version of ABM. However, we can still add same project twice in a collection. Is this allowed?

![image](https://user-images.githubusercontent.com/24721077/55560779-3e123b00-56f1-11e9-97a8-d3d7d8d86726.png)

**Comment by bhermann** [comment]
This should not be allows... a Maven project with the same groupId, artifactId, and version should only allowed to be once in a collection

**Comment by ankur-1989** [comment]
It has been resolved. Now onwards same project won't be added against one version twice. Changes are in development now. Therefore, closing the issue.
