### ISSUE TITLE
Delphi services integration

### ISSUE THREAD

**Issue by Chinmay-92** [ABenchM/abm#234]
here is the query language from Delphi https://github.com/delphi-hub/delphi-webapi/blob/develop/src/main/scala/de/upb/cs/swt/delphi/querylanguage/Syntax.scala
( https://github.com/delphi-hub/delphi-webapi )

Tests are here if you want some examples of queries that work or not https://github.com/delphi-hub/delphi-webapi/blob/develop/src/test/scala/de/upb/cs/swt/delphi/querylanguage/SyntaxTest.scala

- Setup a meeting with Delphi team to discuss / request for demo of these queries.

- [ ] Integration with delphi via frontend

- [ ] DSL parsing and frontend services methods to call advanced query filters

**Comment by Chinmay-92** [comment]
@johannesduesing & @janniclas Could you please provide us updated linkss for SyntaxTest.Scala and Syntax.scala delphi-webapi.
Resources have been moved to some other location.

**Comment by Chinmay-92** [comment]
updated links: 
[https://github.com/delphi-hub/delphi-webapi/blob/develop/src/test/scala/de/upb/cs/swt/delphi/webapi/search/querylanguage/SyntaxTest.scala](url)

**Comment by johannesduesing** [comment]
Hey @Chinmay-92 ,
i think it's best if we discuss that during the next meeting on Thursday. Since we as the PG did not work on the query DSL or anything related to Hermes filtering, i think it is best to get Ben on board for that.
@bhermann is it possible for you to give us a brief overview over the query syntax of Delphi on next Thursday ?

**Comment by bhermann** [comment]
Yes of course!

**Comment by Chinmay-92** [comment]
Below are some links where @vishaljcj and I were looking for the solution:
Most of these fixes tell that config changes must be done on server side.
When we checked server configuration via curl -H command, it has these options already set.

[https://daveceddia.com/access-control-allow-origin-cors-errors-in-angular/](https://daveceddia.com/access-control-allow-origin-cors-errors-in-angular/)

[https://stackoverflow.com/questions/25870199/angularjs-cross-origin-request-blocked](https://stackoverflow.com/questions/25870199/angularjs-cross-origin-request-blocked)

**Comment by johannesduesing** [comment]
Hey @Chinmay-92, what exactly is the issue you are facing? Can you maybe provide some error messages / steps to reproduce ?

**Comment by Chinmay-92** [comment]
Steps to reproduce ( same steps as running abmfrontend ):

1. node index.js
2. go to localhost:3000/login  ( no need to login )
3. click query button

file to check search post method: delphi.service.ts

**Comment by Chinmay-92** [comment]
one more stackoverflow answer: https://stackoverflow.com/questions/20035101/why-does-my-javascript-get-a-no-access-control-allow-origin-header-is-present

**Comment by janniclas** [comment]
hi @Chinmay-92,
I had a quick look at your express server defined in the index.js and to me it seems like it is not configured to allow the cors request. 
Have a look at this article, which shows how to configure an express server to allow cors requests https://medium.freecodecamp.org/the-best-ways-to-connect-to-the-server-using-angular-cli-b0c6b699716c
Setting the headers on the client side won't have any effect since you can't allow cors requests from the client side, which is kinda the point of the cors policy.

**Comment by Chinmay-92** [comment]
After trying both approaches in the above link and discussion with Jan,
we have decided to write API in the backend to call delphi api/features and api/search to avoid CORS blocked issue.
followed by Json deserialization and parsing.
