### ISSUE TITLE
Match Website visuals with collection view

### ISSUE THREAD

**Issue by SwapnilShahGit** [ABenchM/abm#69]

**Comment by Chinmay-92** [comment]
Hi could you please provide description on this?
Also, if this is frontend issue / backend.

**Comment by nguyenLisa** [comment]
Hi, @SwapnilShahGit has left the project since April. Him and his team had come up with new visuals for a Collection (https://github.com/ABenchM/abm/blob/master/docs/UCOSP.bmpr). He suggested in this issue to make the rest of the website well integrated with those visuals. 
@Chinmay-92 , could you please move this issue in the frontend repository and document it? Thanks!

**Comment by SwapnilShahGit** [comment]
Hi, if there are any questions about this, I am happy to answer.

**Comment by nguyenLisa** [comment]
Great, thanks Swapnil! @Chinmay-92 and his group will be in contact with you for any questions.
